name:            yaml-js
version:         0.3.1
description:     Pure Javascript YAML loader and dumper, ported from PyYAML
main:            ./lib/yaml
repository:
  type:          git
  url:           http://github.com/connec/yaml-js.git
engines:
  node:          '>=8'
devDependencies:
  chai:          ^2.3.0
  coffeescript:  ^2.5.1
  mocha:         ^9.1.1
  plantation:    0.0.19
  sinon:         ^1.17.6
  sinon-chai:    ^2.8.0
  squash:        0.0.18
  yaml-js:       .
license:         WTFPL
